# Generated by Django 4.1.2 on 2022-12-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papahapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breach',
            name='breach_datetime',
        ),
    ]
